import { FieldDef, FieldType, PanelField, LayoutPanel, normalizeFieldType } from '@/lib/schema';

/**
 * List of auto-generated field names (bare, without object prefix).
 * These are never validated for required-ness.
 */
const AUTO_GENERATED_FIELD_NAMES = [
  'propertyNumber',
  'contactNumber',
  'accountNumber',
  'leadNumber',
  'dealNumber',
  'productCode',
  'projectNumber',
  'quoteNumber',
  'serviceNumber',
  'installationNumber',
];

/**
 * Check whether a FieldDef represents an auto-generated field that should
 * skip required-field validation.
 */
function isAutoGenerated(fieldDef: FieldDef): boolean {
  return (
    fieldDef.type === 'AutoNumber' ||
    fieldDef.type === 'AutoUser' ||
    fieldDef.type === 'Formula' ||
    fieldDef.type === 'RollupSummary' ||
    (fieldDef.type === 'URL' && !!fieldDef.staticUrl) ||
    AUTO_GENERATED_FIELD_NAMES.includes(fieldDef.apiName.replace(/^\w+__/, ''))
  );
}

/**
 * Validate a set of fields against the current form data.
 *
 * @param fields   Array of `{ panelField, fieldDef }` pairs to validate.
 * @param formData Current form values keyed by field apiName.
 * @returns        A `Record<fieldApiName, errorMessage>` (empty if valid).
 */
export function validateFields(
  fields: Array<{ panelField: PanelField; fieldDef: FieldDef }>,
  formData: Record<string, any>,
): Record<string, string> {
  const errors: Record<string, string> = {};

  for (const { panelField, fieldDef } of fields) {
    const value = formData[panelField.fieldApiName];

    if (isAutoGenerated(fieldDef)) continue;

    // ── Required checks ──────────────────────────────────────────
    const isRequired = fieldDef.required || panelField.behavior === 'required';
    if (isRequired) {
      let empty = value === undefined || value === null || value === '';

      // PicklistText: treat { picklist: '', text: '' } as empty
      if (
        fieldDef.type === 'PicklistText' &&
        typeof value === 'object' &&
        value !== null
      ) {
        if (!value.picklist && !value.text) empty = true;
      }

      // PicklistLookup: treat { picklist: '', lookup: '' } as empty
      if (
        fieldDef.type === 'PicklistLookup' &&
        typeof value === 'object' &&
        value !== null
      ) {
        if (!value.picklist && !value.lookup) empty = true;
      }

      // Address: treat all-empty address as empty
      if (
        fieldDef.type === 'Address' &&
        typeof value === 'object' &&
        value !== null
      ) {
        const parts = [
          value.street,
          value.city,
          value.state,
          value.postalCode,
          value.country,
        ].filter(Boolean);
        if (parts.length === 0) empty = true;
      }

      if (empty) {
        errors[panelField.fieldApiName] = `${fieldDef.label} is required`;
        continue; // no point doing further checks on an empty required field
      }
    }

    // ── Type-specific format checks ──────────────────────────────
    if (value !== undefined && value !== null && value !== '') {
      switch (fieldDef.type) {
        case 'Email':
          if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)) {
            errors[panelField.fieldApiName] = 'Invalid email format';
          }
          break;
        case 'URL':
          try {
            new URL(value);
          } catch {
            errors[panelField.fieldApiName] = 'Invalid URL format';
          }
          break;
        case 'Phone':
          if (!/^[\d\s\-\+\(\)]+$/.test(value)) {
            errors[panelField.fieldApiName] = 'Invalid phone format';
          }
          break;
        case 'Number':
        case 'Currency':
        case 'Percent':
          if (isNaN(Number(value))) {
            errors[panelField.fieldApiName] = 'Must be a valid number';
          }
          break;
      }
    }

    // ── Min / Max bounds ─────────────────────────────────────────
    if (value !== undefined && value !== null && value !== '') {
      if (fieldDef.min !== undefined && Number(value) < fieldDef.min) {
        errors[panelField.fieldApiName] = `Value must be at least ${fieldDef.min}`;
      }
      if (fieldDef.max !== undefined && Number(value) > fieldDef.max) {
        errors[panelField.fieldApiName] = `Value must be at most ${fieldDef.max}`;
      }
    }

    // ── Length constraints ───────────────────────────────────────
    if (typeof value === 'string') {
      if (
        fieldDef.minLength !== undefined &&
        value.length < fieldDef.minLength
      ) {
        errors[panelField.fieldApiName] =
          `Must be at least ${fieldDef.minLength} characters`;
      }
      if (
        fieldDef.maxLength !== undefined &&
        value.length > fieldDef.maxLength
      ) {
        errors[panelField.fieldApiName] =
          `Must be at most ${fieldDef.maxLength} characters`;
      }
    }
  }

  return errors;
}
