export const DEFAULT_TAB_ORDER = [
  { name: 'Properties', href: '/properties' },
  { name: 'Contacts', href: '/contacts' },
  { name: 'Accounts', href: '/accounts' },
  { name: 'Products', href: '/products' },
  { name: 'Leads', href: '/leads' },
  { name: 'Opportunities', href: '/opportunities' },
  { name: 'Projects', href: '/projects' },
  { name: 'Service', href: '/service' },
  { name: 'Work Orders', href: '/workorders' },
  { name: 'Tech Dashboard', href: '/tech-dashboard' },
  { name: 'Quotes', href: '/quotes' },
  { name: 'Installations', href: '/installations' },
  { name: 'Tasks', href: '/tasks' },
  { name: 'Reports', href: '/reports' },
  { name: 'Dashboards', href: '/dashboard' },
];
