export const DEFAULT_TAB_ORDER = [
  { name: 'Properties', href: '/properties' },
  { name: 'Contacts', href: '/contacts' },
  { name: 'Accounts', href: '/accounts' },
  { name: 'Products', href: '/products' },
  { name: 'Leads', href: '/leads' },
  { name: 'Deals', href: '/deals' },
  { name: 'Projects', href: '/projects' },
  { name: 'Service', href: '/service' },
  { name: 'Quotes', href: '/quotes' },
  { name: 'Installations', href: '/installations' },
  { name: 'Summary', href: '/summary' },
  { name: 'Reports', href: '/reports' },
  { name: 'Dashboards', href: '/dashboard' },
];
